language: minimal

sudo: required

services:
  - docker

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull "$DOCKER_USERNAME"/hoomd-core:latest

jobs:
  include:
    - stage: core
      script:
        - docker build -t "$DOCKER_USERNAME"/hoomd-core --cache-from "$DOCKER_USERNAME"/hoomd-core:latest core
        - |
          if [ "$TRAVIS_TAG" ]; then
            docker tag "$DOCKER_USERNAME"/hoomd-core "$DOCKER_USERNAME"/hoomd-core:"$TRAVIS_TAG"
          fi
        - docker push "$DOCKER_USERNAME"/hoomd-core

    - stage: hoomd
      script:
        - docker build -t "$DOCKER_USERNAME"/hoomd .
        - docker run "$DOCKER_USERNAME"/hoomd python36 -c "import hoomd"
        - docker push "$DOCKER_USERNAME"/hoomd
