language: minimal

sudo: required

services:
  - docker

install:
  - docker pull malramsay/hoomd-core

jobs:
  include:
    - stage: core
      script: docker build -t malramsay/hoomd-core core
    - stage: hoomd
      script: docker build -t malramsay/hoomd .
    - stage: test
      script: docker run malramsay/hoomd python36 -c "import hoomd"

deploy:
  provider: script
  script: ./docker_push
  on:
    branch: master
